esphome:
  name: batt
  friendly_name: batt

esp8266:
  board: d1_mini

logger:
api:
ota:
  - platform: esphome

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  ap: {}
  manual_ip: 
    static_ip: 192.168.0.6
    gateway: 192.168.0.1
    subnet: 255.255.255.0
captive_portal:
web_server: