substitutions:
  relay1_pin: GPIO12
  relay2_pin: GPIO14
  switch1_pin: GPIO5
  switch2_pin: GPIO4
  statusled_pin: GPIO2

esphome:
  name: front-room
  friendly_name: Front Room
  project:
    name: "MDtronix.2ch smart switch"
    version: "1.0"
    
esp8266:
  board: esp8285

logger:
api:
debug:
ota:
  - platform: esphome

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  ap: {}

captive_portal:
web_server:

output:
  - platform: gpio
    pin: $relay1_pin
    id: relay1_id
  - platform: gpio
    pin: $relay2_pin
    id: relay2_id

light:
  - platform: binary
    output: relay1_id
    name: Bulb
    id: relay_id_1
    restore_mode: RESTORE_DEFAULT_OFF

fan:
  - platform: binary
    output: relay2_id
    name: Fan
    id: relay_id_2
    restore_mode: RESTORE_DEFAULT_OFF

binary_sensor:
  - platform: gpio
    id: switch_id_1
    pin:
      number: $switch1_pin
      mode: INPUT_PULLUP
      inverted: True
    on_state:
      - light.toggle: relay_id_1

  - platform: gpio
    id: switch_id_2
    pin:
      number: $switch2_pin
      mode: INPUT_PULLUP
      inverted: True
    on_state:
      - fan.toggle: relay_id_2

status_led:
  pin: $statusled_pin

text_sensor:
  - platform: debug
    reset_reason:
      name: "Reset Reason"     

button:
  - platform: restart
    name: restart        